# title of website
title: HM site

# description of website
description: HM's navigation site

# favicon of website
favicon: "https://github.com/a1609jk.png?size=40"

# your website url
url: https://a1609jk.github.io/jp/

# github profile url
github: "https://github.com/a1609jk"

# footer message
footer: © 2024-2024 @HM

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - baidu
      - bing

content:
  categories:
    - name: 合作商网站
      sites:
        - name: イオン　ネット
          description: イオン生活用品网贩平台
          url: https://aeonretail.com/
        - name: しまむら
          description: 島村公式店铺
          url: https://www.shop-shimamura.com/?b=shimamura        
        - name: ドン・キホーテ
          description: ドン・キホーテ商品紹介
          url: https://www.donki.com/j-kakaku/product/list.php?cid=27
        - name: 島忠
          description: 家居专门店
          url: https://netshop.shimachu.co.jp/shop/
        - name: イケヒコ
          description: イケヒコ公式店铺
          url: https://www.ikehikoshop.jp
        - name: 株式会社ロマンス小杉
          description: 株式会社ロマンス小杉公式店铺
          url: https://shop.atelierofsleep.com
        - name: モダンデコ楽天店
          description: 可进主页
          url: https://www.rakuten.ne.jp/gold/dondon/
        - name: 布団と寝具専門店 colors
          description: 店铺主页打不开，请从商品页面看
          url: https://item.rakuten.co.jp/futon-colors/c/         
        - name: タンスのゲン楽天店
          description: 可进主页
          url: https://www.rakuten.ne.jp/gold/tansu/  
        - name: LOWYA（ロウヤ）楽天店
          description: 可进主页
          url: https://www.rakuten.ne.jp/gold/low-ya/      
    - name: 综合电商
      sites:
        - name: 日本亚马逊
          description: 全球电商平台，可切换国家
          url: https://www.amazon.co.jp/
        - name: 日本乐天
          description: 请直接打开，直接搜索，主页现ip无法访问
          url: https://search.rakuten.co.jp/search/mall/%E5%AF%9D%E5%85%B7/
        - name: 日本雅虎
          description: 日本三大电商平台之一
          url: https://shopping.yahoo.co.jp/
        - name: BicCamera
          description: 日本综合性实体电商的寝具类目
          url: https://www.biccamera.com/bc/category/001/190/
        - name: ヨドバシ
          description: 日本综合性实体电商的寝具类目
          url: https://www.yodobashi.com/category/162842/163358/
        - name: Joshinweb
          description: 日本综合性较强的电商寝具类目
          url: https://joshinweb.jp/interior/4588.html
        - name: イトーヨーカドー
          description: 电商实体
          url: hhttps://iyec.itoyokado.co.jp   
        - name: ジャパネット
          description: 电商平台
          url: https://www.japanet.co.jp/shopping/
        - name: ニトリ
          description: nitori一站式家居电商实体
          url: https://www.nitori-net.jp/ec/
        - name: MUJI
          description: 无印一站式家居电商实体
          url: https://www.muji.com/jp/ja/store
        - name: IRIS
          description: アイリスオーヤマ公式サイト
          url: https://www.irisplaza.co.jp
        - name: ショップジャパン
          description: ショップジャパン
          url: https://www.shopjapan.co.jp  
        - name: dinos
          description: dinos的寝具类目
          url: https://www.dinos.co.jp/c2/002008/
        - name: Makuake
          description: 日本众筹平台趋势分享
          url: https://www.makuake.com  
        - name: BestOne
          description: 日本版什么值得买
          url: https://my-best.com          
    - name: 拓展推荐
      sites:
        - name: 日本亚马逊站热搜词
          description: 日本站前25w搜索词，一周更新一次
          url: https://www.amz123.com/jptopkeywords
        - name: 日亚新品榜
          description: 日亚新品上架排行榜
          url: https://www.amazon.co.jp/gp/new-releases/
        - name: 日亚销售榜
          description: 日亚销售排行榜
          url: https://www.amazon.co.jp/gp/bestsellers
        - name: 日亚飙升榜
          description: 日亚排名飙升排行
          url: https://www.amazon.co.jp/gp/movers-and-shakers/          
        - name: 谷歌趋势
          description: 查看关键词在日本谷歌的搜索次数及变化趋势
          url: https://trends.google.com/trends/?geo=JP
        - name: 価格
          description: 参考左侧寝具类目关键词排行
          url: https://kakaku.com/interior/
        - name: 日本纺织纤维企业名目
          description: 日经新闻汇总企业一览
          url: https://www.nikkei.com/nkd/industry/complist/?n_m_code=021
        - name: 日本企业纺织协会
          description: 可查看会员会社
          url: http://www.jsa-jp.org/
        - name: 繊維製品業界 売上高ランキング
          description: 非官方
          url: https://www.buffett-code.com/industries/5
    - name: 常用工具推荐
      sites:
        - name: 日元实时汇率
          description: 日元汇率及趋势
          url: https://www.amz123.com/tools-hlhs/jpy/cny
        - name: 美元实时汇率
          description: 美元汇率实时变化
          url: https://gushitong.baidu.com/foreign/global-USDCNY
        - name: 海关编码查询
          description: 日本海关关税税率查询
          url: https://www.customs.go.jp/tariff/index.htm
        - name: 日本商标专利查询
          description: 日本商标专利简易搜索
          url: https://www.j-platpat.inpit.go.jp/s0100 
        - name: 日本假日日历
          description: 可查各国假期日历
          url: https://www.timeanddate.com/calendar/?year=2021&country=26
        - name: 出口退税率查询
          description: 出口退税率查询
          url: https://hd.chinatax.gov.cn/nszx/InitChukou.html
        - name: 海运航线查询
          description: 海运日时查询
          url: http://www.shippingaccess.com/schedule/
    - name: 新闻平台
      sites:
        - name: 日本经济新闻
          description: 日本经济新闻网站
          url: https://www.nikkei.com/
        - name: 朝日新闻
          description: 日本网络最大的新闻网站
          url: https://www.asahi.com/
        - name: 每日新闻
          description: 日本新鲜新闻
          url: https://mainichi.jp/
        - name: 产经新闻
          description: 日本产业经济新闻网
          url: https://www.sankei.com/
        - name: 通贩通信
          description: ec，通贩类新闻
          url: https://ecnomikata.com
        - name: 纺织快讯
          description: 全球纺织网，纺织快讯，有面料行情
          url: https://www.tnc.com.cn/info/c001.html
        - name: 中国纺织经济信息网
          description: 纺织业行情，纺织快讯，有面料行情
          url: http://www.ctei.cn
        - name: 棉纺织信息网
          description: 棉纱原料行情
          url: https://www.tteb.com/



